# Site settings
title: Adam Raider
description: > # this means to ignore newlines until "baseurl:"
  Half-formed thoughts of a software dev
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://adamraider.github.io" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown
permalink: /:title/
# Sass settings
sass:
  add_charset: true
  sass_dir: _sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
